### ISSUE TITLE
VSCode link in the readme points to the wrong repo

### ISSUE THREAD

**Issue by LennyLixalot** [Almenon/AREPL#69]
As title, currently the link points to the releases for this repo instead, I had to search "vscode" in the issues to find the extension.

**Comment by Almenon** [comment]
Fixed. Thanks for pointing that out!  If i may ask - how did you find AREPL?  How do you like the vscode extension (if you tried it)?

**Comment by LennyLixalot** [comment]
To be hones it didn't actually work, I was going to investigate the issue and then file an issue here but I didn't do that yet as I wanted to focus on the actual code I was writing. Aaaand I just tried it again to get the error and it's working now... Maybe it was just a first-run issue? I remember that I tried executing the command in VSCode and it gave me an error and never opened the pane, but I don't remember what the error was, sorry... This is a really unhelpful report.

I think I'll probably end up actually using it properly later today, so I'll come back here if I've got any good feedback for you. Initial thought is that it's cool.

If you want a challenge, there's a really cool VSCode extension for javascript called Quokka that can do stuff a bit like this, but that displays prints inline in the code. That would be nice to have in Python, but I imagine it might be a big step up in complexity if you copied all of the Quokka features.

**Comment by Almenon** [comment]
That's odd.... What OS do you have?

I actually use Quoakka, it's pretty cool I agree.  I'll raise some issues for the feaures you mentioned.

A inline exception should be pretty easy to implement.  

https://github.com/Almenon/AREPL-vscode/issues/3

Not sure how I would do inline printing, however.  I'd have to somehow match up the line numbers with each print statement.  And there can be multiple items printed on a single line, too.

https://github.com/Almenon/AREPL-vscode/issues/4
