### ISSUE TITLE
AREPL on Linux does not recognise python

### ISSUE THREAD

**Issue by ItsDrike** [Almenon/AREPL#89]
I'm running vscode on Linux (Ubuntu bionic) and when I installed AREPL extension, it gives this error:
```
Error in the AREPL extension!
Error running python with command: C:\Python38-32\python.exe -u /home/koumakpet/.vscode/extensions/almenon.arepl-1.0.20/node_modules/arepl-backend/python/python_evaluator.py
Error: spawn C:\Python38-32\python.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)

Are you sure you have installed python 3 and it is in your PATH?
            You can download python here: https://www.python.org/downloads/
```
it seems as if it searched windows path for python instead of the linux one
My python is under: **/usr/bin/python3**

**Comment by koumakpet** [comment]
I'm not sure if the issue should be here or in AREPL-vscode repository so I posted it in both.

**Comment by ItsDrike** [comment]
I posted the issue in AREPL-vscode, where it should be instead of this electron repository.

> The issue was that it took windows path instead of linux path, and it could have been changed in vscode settings by:
> `AREPL.pythonPath = "/usr/bin/python3"`
